from enum import Enum


questions_equivs = {
    'Tecnología': 'TECNOLOGIA', 
    'Cooperativismo': 'COOPS', 
    'Software libre': 'SOFTWARE_LIBRE', 
    'Comunicación': 'COMUNICACION ', 
    'Palomar/Morón': 'PALOMAR_MORON', 
    'Huella digital': 'HUELLA_DIGITAL'}

LABELS = list(questions_equivs.keys())

class Questions(Enum):
COOPS = [
    ("¿El cooperativismo argentino tiene sus raíces en el siglo XIX?", True),
    ("¿Las cooperativas en Argentina pueden operar en cualquier sector económico?", True),
    ("¿Es obligatorio que una cooperativa argentina distribuya todos sus excedentes entre sus miembros?", False),
    ("¿Pueden las cooperativas argentinas recibir beneficios fiscales?", True),
    ("¿La membresía en una cooperativa argentina es limitada a un número fijo de personas?", False),
    ("¿Es necesario que todas las cooperativas en Argentina tengan un Consejo de Administración?", True),
    ("¿El INAES es el organismo que regula las cooperativas en Argentina?", True),
    ("¿Una cooperativa argentina puede ser transformada en una sociedad anónima?", False),
    ("¿Las cooperativas argentinas tienen que cumplir con la Ley de Cooperativas N° 20.337?", True),
    ("¿Es obligatorio que los miembros de una cooperativa tengan igualdad de votos?", True),
    ("Existe una cooperativa en Australia que fabrica colchones para canguros", False),
    ("En Japón, hay cooperativas que ofrecen alquiler de amigos para actividades sociales y eventos ", True),
    ("Existe una cooperativa en Francia que produce perfume de lavanda para sus miembros.", False),
    ("En Italia, hay una cooperativa que restaura y alquila castillos", True),
    ("En Argentina existe una cooperativa de artistas callejeros", True),
    ("En Argentina existe una cooperativa que exporta miel a más de 20 países.", True),
    ("Las cooperativas se pueden organizar en federaciones y confederaciones.", True)
]

COMUNICACION = [
    ("¿La comunicación verbal incluye tanto el lenguaje hablado como el escrito?", True),
    ("¿La comunicación no verbal es menos importante que la comunicación verbal?", False),
    ("¿El lenguaje corporal es un tipo de comunicación no verbal?", True),
    ("¿La escucha activa significa simplemente oír lo que dice otra persona?", False),
    ("¿El tono de voz puede cambiar el significado de un mensaje?", True),
    ("¿La retroalimentación es importante para asegurar que el mensaje fue comprendido?", True),
    ("¿El emisor es la persona que recibe el mensaje?", False),
    ("¿El receptor es la persona que envía el mensaje?", False),
    ("¿La comunicación escrita no requiere retroalimentación?", False),
    ("¿Los emojis en mensajes de texto son ejemplos de comunicación no verbal?", True),
    ("¿El contexto no afecta el significado de un mensaje?", False),
    ("¿Un canal de comunicación puede ser oral, escrito o visual?", True),
    ("¿La barrera de ruido en la comunicación puede ser física o psicológica?", True),
    ("¿El código de comunicación debe ser conocido tanto por el emisor como por el receptor?", True),
    ("¿La comunicación unidireccional permite retroalimentación inmediata?", False),
    ("¿La comunicación puede influir en las relaciones personales y profesionales?", True),
    ("¿El lenguaje inclusivo es una forma de evitar estereotipos en la comunicación?", True),
    ("¿Un mensaje ambigüo es fácil de comprender?", False),
    ("¿Los gestos y expresiones faciales son parte de la comunicación verbal?", False),
    ("¿La empatía puede mejorar la comunicación interpersonal?", True),
    ("¿El ruido puede hacer que un mensaje se malinterprete?", True),
    ("¿Los malentendidos en comunicación pueden ser causados por barreras culturales?", True),
    ("¿El lenguaje formal es apropiado en todos los contextos de comunicación?", False),
    ("¿La comunicación visual incluye imágenes, gráficos y videos?", True),
    ("¿La comunicación efectiva depende únicamente del emisor?", False),
    ("¿El feedback en la comunicación solo puede ser verbal?", False),
    ("¿El mensaje en la comunicación es la información que se quiere transmitir?", True),
    ("¿El lenguaje corporal tiene el mismo significado en todas las culturas?", False),
    ("¿El silencio también puede comunicar algo en una conversación?", True),
    ("¿Las barreras de comunicación siempre se pueden eliminar por completo?", False),
    ("¿La comunicación asertiva implica expresar tus ideas respetando las de los demás?", True),
    ("¿La comunicación interpersonal es aquella que se da en redes sociales?", False),
    ("¿La habilidad de comunicar bien es importante solo para ciertas profesiones?", False),
    ("¿Las emociones afectan la manera en que nos comunicamos?", True),
    ("¿La comunicación interpersonal se refiere solo a comunicación entre dos personas?", False),
    ("¿El canal digital facilita la comunicación en tiempo real?", True),
    ("¿Un buen comunicador siempre utiliza palabras complicadas para impresionar?", False),
    ("¿La comunicación efectiva puede ayudar a evitar conflictos?", True),
    ("¿El entorno en el que se da la comunicación no afecta el mensaje?", False),
    ("¿El lenguaje verbal es la única forma de transmitir información compleja?", False),
    ("¿La comunicación formal requiere un lenguaje y tono específicos?", True),
    ("¿El receptor puede influir en la forma en que el mensaje es interpretado?", True),
    ("¿La comunicación intrapersonal es la que ocurre dentro de uno mismo?", True),
    ("¿La escucha activa implica poner atención y responder al mensaje del emisor?", True),
    ("¿El tono de voz no afecta el significado de una pregunta?", False),
    ("¿La comunicación cara a cara es un ejemplo de comunicación directa?", True),
    ("¿En una carta formal se debe usar un lenguaje informal y casual?", False),
    ("¿Los prejuicios pueden ser una barrera para la comunicación efectiva?", True),
    ("¿La comunicación escrita es siempre más clara que la verbal?", False),
    ("¿La comunicación digital incluye correos electrónicos, mensajes y redes sociales?", True),
]

HUELLA_DIGITAL = [
    ("¿La huella digital se refiere a la información que dejamos al navegar por internet?", True),
    ("¿La huella digital es siempre visible para nosotros en todo momento?", False),
    ("¿Usar contraseñas fuertes y únicas para cada cuenta mejora nuestra seguridad en internet?", True),
    ("¿La huella digital se puede borrar por completo una vez creada?", False),
    ("¿Es seguro compartir información personal en redes sociales sin restricciones de privacidad?", False),
    ("¿La autenticación de dos factores añade una capa extra de seguridad a nuestras cuentas?", True),
    ("¿La huella digital puede afectar nuestra reputación profesional en el futuro?", True),
    ("¿La huella digital pasiva es creada sin nuestra intervención directa, por ejemplo, con cookies de seguimiento?", True),
    ("¿Los navegadores en modo incógnito eliminan toda nuestra huella digital de internet?", False),
    ("¿Es recomendable revisar las políticas de privacidad de las aplicaciones que instalamos?", True),
    ("¿Es seguro hacer clic en enlaces o abrir archivos de fuentes desconocidas?", False),
    ("¿La huella digital activa es la información que publicamos intencionalmente en internet?", True),
    ("¿Las redes Wi-Fi públicas son seguras para realizar transacciones bancarias?", False),
    ("¿Es importante revisar y ajustar la configuración de privacidad en nuestras redes sociales?", True),
    ("¿Usar aplicaciones de gestión de contraseñas puede mejorar nuestra seguridad en línea?", True),
    ("¿Compartir nuestra ubicación en redes sociales no tiene riesgos de seguridad?", False),
    ("¿El phishing es una técnica para robar información haciéndose pasar por entidades legítimas?", True),
    ("¿No es necesario cerrar sesión en nuestras cuentas cuando usamos un dispositivo compartido?", False),
    ("¿La información que eliminamos de internet desaparece por completo y no puede recuperarse?", False),
    ("¿Mantener el software de nuestros dispositivos actualizado ayuda a proteger nuestra información?", True),
    ("¿La ingeniería social es una técnica que explota la confianza de las personas para obtener datos?", True),
    ("¿Compartir contraseñas con amigos y familiares es una buena práctica de seguridad?", False),
    ("¿Las empresas pueden recopilar y vender nuestra huella digital para fines publicitarios?", True),
    ("¿El uso de VPN (Red Privada Virtual) puede ayudar a proteger nuestra privacidad en internet?", True),
    ("¿Nuestra huella digital puede incluir información sobre nuestras preferencias y hábitos de consumo?", True),
    ("¿Es seguro utilizar la misma contraseña para todas nuestras cuentas en línea?", False),
    ("¿Las cookies almacenan datos de navegación que pueden usarse para personalizar la publicidad?", True),
    ("¿Podemos limitar la cantidad de información personal disponible en internet ajustando la configuración de privacidad?", True),
    ("¿La suplantación de identidad (phishing) se puede evitar revisando cuidadosamente los correos electrónicos sospechosos?", True),
    ("¿La huella digital solo afecta a personas que tienen redes sociales?", False),
    ("¿Un archivo malicioso puede infectar nuestro dispositivo solo con descargarlo?", True),
    ("¿Los datos de nuestra huella digital pueden ser usados para crear perfiles de consumidor?", True),
    ("¿Utilizar diferentes correos electrónicos para distintas actividades puede proteger mejor nuestra privacidad?", True),
    ("¿Los términos y condiciones no afectan a cómo se usa nuestra información personal en una aplicación?", False),
    ("¿Publicar menos información en línea ayuda a reducir nuestra huella digital?", True),
    ("¿Las aplicaciones siempre requieren acceso a toda nuestra información para funcionar?", False),
    ("¿El 'ransomware' es un tipo de ataque que bloquea el acceso a nuestros archivos hasta pagar un rescate?", True),
    ("¿Es seguro aceptar solicitudes de amistad o conexión de personas que no conocemos?", False),
    ("¿Desactivar el historial de ubicación en el teléfono puede ayudar a proteger nuestra privacidad?", True),
    ("¿Usar sitios web con 'https://' en la URL es más seguro que con 'http://'?", True),
    ("¿El 'malware' es software malicioso diseñado para dañar o robar información?", True),
    ("¿Es una buena práctica usar preguntas de seguridad fáciles de adivinar para recuperar nuestras contraseñas?", False),
    ("¿La autenticación biométrica, como el reconocimiento facial, añade seguridad a nuestras cuentas?", True),
    ("¿Es posible reducir la huella digital pasiva usando bloqueadores de rastreadores y cookies?", True),
    ("¿Una vez que una foto o video se publica en internet, siempre es fácil de borrar de todas las plataformas?", False),
    ("¿Leer reseñas y permisos de una aplicación antes de instalarla puede ayudarnos a proteger nuestra privacidad?", True),
    ("¿Las copias de seguridad ayudan a recuperar archivos en caso de un ataque o pérdida de datos?", True),
    ("¿El 'scareware' intenta asustar al usuario para que descargue software malicioso?", True),
    ("¿Usar nombres reales en foros y comentarios siempre es una buena práctica?", False),
    ("¿Desconfiar de correos o mensajes que piden datos personales puede ayudarnos a evitar fraudes?", True),
]

PALOMAR_MORON = [
    ("¿El Palomar es una ciudad ubicada en la provincia de Buenos Aires?", True),
    ("¿El Hospital Posadas está ubicado en El Palomar?", True),
    ("¿El Palomar pertenece al partido de Morón?", True),
    ("¿El aeropuerto de El Palomar fue el primer aeropuerto low-cost de Argentina?", True),
    ("¿El Palomar tiene una estación de tren de la línea San Martín?", True),
    ("¿El Museo Nacional de Aeronáutica está ubicado en El Palomar?", True),
    ("¿Morón es una ciudad del Gran Buenos Aires?", True),
    ("¿El municipio de Morón se compone de cinco localidades?", True),
    ("¿La Base Aérea de El Palomar fue inaugurada en 1919?", True),
    ("¿Morón fue uno de los primeros partidos fundados en la provincia de Buenos Aires?", True),
    ("¿La Universidad de Morón es una universidad pública?", False),
    ("¿La Catedral de Morón está dedicada a Nuestra Señora del Buen Viaje?", True),
    ("¿El Festival de la Destreza Criolla y la Canción Folklórica se celebra en Morón?", True),
    ("¿La estación de tren de Morón pertenece a la línea Roca?", False),
    ("¿Morón cuenta con un centro cultural llamado Plaza Oeste?", False),
    ("¿El Partido de Morón tiene salida al Río de la Plata?", False),
    ("¿El centro de Morón tiene un paseo de compras conocido como Plaza Morón?", False, "El centro cuenta con zonas comerciales, pero no un paseo llamado Plaza Morón"),
    ("¿La línea de tren Sarmiento pasa por Morón?", True),
    ("¿El Palomar está conectado con Morón a través de la Avenida Presidente Perón?", True),
    ("¿La Ciudad de Morón celebra el Día de la Virgen del Buen Viaje como una festividad local?", True),
    ("¿Morón fue parte del Camino Real durante la época colonial?", True),
    ("¿La Base Aérea de El Palomar ha sido utilizada para vuelos comerciales y militares?", True),
    ("¿La Universidad de Morón fue fundada en 1960?", True),
    ("¿El Hospital Municipal de Morón lleva el nombre de su fundador?", True, "Se llama Hospital Municipal de Morón Ostaciana B. de Lavignolle"),
    ("¿El centro de El Palomar cuenta con áreas históricas y un fuerte inglés?", False),
    ("¿La estación Morón es una de las más antiguas de la línea Sarmiento?", True),
    ("¿El Barrio Gaona es una de las zonas comerciales de Morón?", True),
    ("¿El Palomar cuenta con un gran parque central llamado 'Plaza El Palomar'?", False),
    ("¿El Club Morón fue fundado en 1947?", True),
    ("¿Morón es conocido por su tradición en la producción vitivinícola?", False),
    ("¿La localidad de Castelar es parte del partido de Morón?", True),
    ("¿El Palomar tiene un teatro emblemático llamado Teatro Gregorio de Laferrere?", False),
    ("¿El Club Deportivo Morón tiene un estadio conocido como el Nuevo Francisco Urbano?", True),
    ("¿La Municipalidad de Morón tiene su sede en Haedo?", False, "La sede está en la ciudad de Morón"),
    ("¿La Universidad de Morón tiene una escuela de aviación?", True),
    ("¿El aeropuerto de El Palomar era originalmente un aeródromo militar?", True),
    ("¿El Polideportivo Gorki Grana se encuentra en Morón?", True),
    ("¿La Biblioteca Municipal de Morón se encuentra en Castelar?", False),
    ("¿El municipio de Morón celebra la Fiesta de la Vendimia cada año?", False),
    ("¿El Palomar limita con el partido de Hurlingham?", True),
    ("¿El Club de Rugby Curupaytí se encuentra en El Palomar?", True),
    ("¿La estación de tren Haedo pertenece al partido de Morón?", True),
    ("¿Morón tiene un hospital que fue pionero en la atención gratuita en Buenos Aires?", True, "El Hospital Municipal de Morón fue pionero en la atención gratuita"),
    ("¿La línea de tren San Martín pasa por Morón?", False, "La línea San Martín pasa por El Palomar, pero no por Morón"),
    ("¿El Estadio Francisco Urbano está dedicado a eventos de polo?", False, "Es un estadio de fútbol"),
    ("¿La avenida Rivadavia es una de las principales vías de Morón?", True),
    ("¿La plaza central de Morón es conocida como Plaza de la Virgen del Buen Viaje?", False, "Es la Plaza General San Martín"),
    ("¿La Casa de la Memoria y la Vida en Morón es un espacio dedicado a la memoria histórica?", True),
    ("¿La Universidad Tecnológica Nacional tiene una sede en Morón?", True),
    ("¿El Centro Comercial Oeste, o Plaza Oeste, se encuentra en Morón?", True),
    ("¿La localidad de Villa Sarmiento pertenece al partido de Morón?", True),
]

SOCIOCULTURALES = [
    ("¿El siglo XXI ha sido marcado por el avance de la globalización?", True),
    ("¿La tecnología digital ha cambiado la forma en que las personas se comunican en el siglo XXI?", True),
    ("¿Las redes sociales comenzaron en el siglo XIX?", False),
    ("¿El cambio climático es una preocupación global en el siglo XXI?", True),
    ("¿Los movimientos por la igualdad de género han tenido gran importancia en el siglo XXI?", True),
    ("¿La migración masiva es un fenómeno destacado en el siglo XXI?", True),
    ("¿El concepto de 'economía colaborativa' se refiere a compartir recursos y servicios?", True),
    ("¿La cultura pop no tiene influencia en los valores de la juventud actual?", False),
    ("¿El acceso a la educación es más equitativo en todas las partes del mundo en el siglo XXI?", False),
    ("¿La diversidad cultural es cada vez más visible gracias a la globalización?", True),
    ("¿Las fake news (noticias falsas) no afectan la opinión pública en la era digital?", False),
    ("¿La digitalización ha permitido el acceso inmediato a la información en el siglo XXI?", True),
    ("¿Los derechos humanos siguen siendo un tema de discusión en la sociedad actual?", True),
    ("¿El cambio hacia energías renovables es una respuesta a la crisis ambiental?", True),
    ("¿El término 'cultura de cancelación' se refiere a acciones de boicot contra figuras públicas?", True),
    ("¿La inteligencia artificial no tiene ningún impacto en el empleo actual?", False),
    ("¿Los movimientos LGBTQ+ han ganado mayor visibilidad en el siglo XXI?", True),
    ("¿La privacidad en internet no es un problema importante en el siglo XXI?", False),
    ("¿Los jóvenes del siglo XXI tienen menos acceso a dispositivos tecnológicos?", False),
    ("¿El e-commerce (comercio en línea) ha cambiado la forma en que compramos y vendemos?", True),
    ("¿Los influencers han ganado popularidad debido a la televisión tradicional?", False),
    ("¿El uso de aplicaciones de mensajería instantánea es parte de la comunicación moderna?", True),
    ("¿La inteligencia artificial es un concepto nuevo del siglo XXI?", False, "Se originó antes, pero ha crecido mucho en este siglo"),
    ("¿El activismo digital permite que las personas apoyen causas desde cualquier lugar?", True),
    ("¿El trabajo remoto (home office) se ha hecho más común en el siglo XXI?", True),
    ("¿La educación en línea no ha tenido crecimiento en el siglo XXI?", False),
    ("¿La desigualdad económica sigue siendo un problema en el mundo actual?", True),
    ("¿Los teléfonos inteligentes han reducido la cantidad de información disponible?", False),
    ("¿Las protestas y movimientos sociales han aumentado con el uso de redes sociales?", True),
    ("¿La cultura de masas ha sido menos influyente con el avance de la globalización?", False),
    ("¿La protección del medio ambiente es una prioridad de muchos gobiernos actuales?", True),
    ("¿La globalización ha llevado a una mayor homogeneización cultural?", True),
    ("¿La inteligencia artificial se usa en áreas como la medicina y la educación?", True),
    ("¿El fenómeno del 'cyberbullying' se ha convertido en un problema en la era digital?", True),
    ("¿La cultura de consumo masivo ha disminuido en el siglo XXI?", False),
    ("¿Las identidades culturales tienden a desaparecer con la globalización?", False, "Algunas se han fortalecido y diversificado"),
    ("¿Los avances en biotecnología pueden cambiar la vida de las personas en el siglo XXI?", True),
    ("¿El entretenimiento digital ha reducido el interés en la literatura tradicional?", False, "Aún existen grandes comunidades lectoras"),
    ("¿El teletrabajo puede ayudar a reducir la contaminación ambiental?", True)
]