from enum import Enum


questions_equivs = {
    'Tecnología': 'TECNOLOGIA', 
    'Cooperativismo': 'COOPS', 
    'Software libre': 'SOFTWARE_LIBRE', 
    'Python': 'PYTHON', 
    'Hurlingham': 'HURLINGHAM', 
    'Programación': 'PROGRAMACION'}

LABELS = list(questions_equivs.keys())

class Questions(Enum):
    COOPS = [
        ("¿El cooperativismo argentino tiene sus raíces en el siglo XIX?", True),
        ("¿Las cooperativas en Argentina pueden operar en cualquier sector económico?", True),
        ("¿Es obligatorio que una cooperativa argentina distribuya todos sus excedentes entre sus miembros?", False),
        ("¿Pueden las cooperativas argentinas recibir beneficios fiscales?", True),
        ("¿La membresía en una cooperativa argentina es limitada a un número fijo de personas?", False),
        ("¿Es necesario que todas las cooperativas en Argentina tengan un Consejo de Administración?", True),
        ("¿El INAES es el organismo que regula las cooperativas en Argentina?", True),
        ("¿Una cooperativa argentina puede ser transformada en una sociedad anónima?", False),
        ("¿Las cooperativas argentinas tienen que cumplir con la Ley de Cooperativas N° 20.337?", True),
        ("¿Es obligatorio que los miembros de una cooperativa tengan igualdad de votos?", True),
        ("Existe una cooperativa en Australia que fabrica colchones para canguros", False),
        ("En Japón, hay cooperativas que ofrecen alquiler de amigos para actividades sociales y eventos ", True),
        ("Existe una cooperativa en Francia que produce perfume de lavanda para sus miembros.", False),
        ("En Italia, hay una cooperativa que restaura y alquila castillos", True),
        ("En Argentina existe una cooperativa de artistas callejeros", True),
        ("En Argentina existe una cooperativa que exporta miel a más de 20 países.", True),
        ("Las cooperativas se pueden organizar en federaciones y confederaciones.", True)
    ]

    PYTHON = [
        ("¿Python es un lenguaje de programación de alto nivel?", True),
        ("¿Python fue creado por Guido van Rossum?", True),
        ("¿Python es un lenguaje de programación compilado?", False),
        ("¿La sintaxis de Python permite el uso de corchetes para delimitar bloques de código?", False),
        ("¿Python soporta programación orientada a objetos?", True),
        ("¿Python es conocido por su simplicidad y legibilidad?", True),
        ("¿Python tiene un gestor de paquetes llamado pip?", True),
        ("¿La extensión de archivo estándar para scripts de Python es .py?", True),
        ("¿Python 2 y Python 3 son completamente compatibles entre sí?", False),
        ("¿Las listas en Python son mutables?", True),
        ("¿Los diccionarios en Python permiten claves duplicadas?", False),
        ("¿Python soporta múltiples herencias?", True),
        ("¿El operador '+' puede ser usado para concatenar cadenas en Python?", True),
        ("¿Las tuplas en Python son mutables?", False),
        ("¿Python tiene recolección automática de basura (garbage collection)?", True),
        ("¿El módulo 'os' permite interactuar con el sistema operativo?", True),
        ("¿Python puede ser usado para desarrollo web?", True),
        ("¿'None' es equivalente a 'False' en Python?", False),
        ("¿El método 'append()' agrega elementos al final de una lista?", True),
        ("¿Python tiene tipos de datos estáticos?", False),
        ("¿El ciclo 'while' en Python necesita una condición booleana?", True),
        ("¿Las funciones lambda pueden tener múltiples expresiones?", False),
        ("¿El operador '==' compara la identidad de los objetos en Python?", False),
        ("¿Se puede definir una función dentro de otra función en Python?", True),
        ("¿El método 'clear()' borra el contenido de una lista?", True),
        ("¿El operador '**' se usa para la exponenciación en Python?", True),
        ("¿El módulo 'math' en Python incluye funciones trigonométricas?", True),
        ("¿Una variable en Python necesita ser declarada con un tipo específico?", False),
        ("¿El statement 'global' permite modificar variables globales dentro de funciones?", True),
        ("¿El tipo 'int' en Python tiene un límite máximo?", False),
        ("¿Python es adecuado para scripting y automatización?", True),
        ("¿Las clases en Python pueden tener métodos estáticos?", True),
        ("¿El operador '//' realiza una división entera en Python?", True),
        ("¿Python tiene una palabra clave llamada 'switch'?", False),
        ("¿Se puede manejar excepciones en Python usando 'try-except'?", True),
        ("¿El método 'pop()' elimina el primer elemento de una lista?", False),
        ("¿El módulo 'json' en Python permite trabajar con JSON?", True),
        ("¿Python es un lenguaje case-sensitive?", True),
        ("¿El statement 'pass' se usa para definir un bloque vacío en Python?", True),
        ("¿El operador 'is' compara la identidad de los objetos?", True),
        ("¿Las listas en Python pueden contener diferentes tipos de datos?", True),
        ("¿La palabra clave 'del' elimina una variable en Python?", True),
        ("¿Python tiene soporte para el concepto de 'closures'?", True),
        ("¿El método 'sort()' modifica la lista original?", True),
        ("¿El ciclo 'for' en Python necesita un contador manual?", False),
        ("¿Se puede definir propiedades en las clases usando 'property()'?", True),
        ("¿Python permite el uso de 'decorators' para modificar el comportamiento de funciones?", True),
        ("¿El método 'remove()' elimina un elemento de una lista por su índice?", False),
        ("¿El statement 'yield' en Python convierte una función en un generador?", True)
    ]

    PROGRAMACION = [
        ("¿La programación orientada a objetos utiliza conceptos como clases y objetos?", True),
        ("¿Un algoritmo siempre debe tener un número infinito de pasos?", False),
        ("¿Un bucle infinito es un tipo de error común en la programación?", True),
        ("¿Los diagramas de flujo se utilizan para representar visualmente algoritmos?", True),
        ("¿En la programación funcional, las funciones pueden ser tratadas como valores?", True),
        ("¿Un compilador traduce código fuente a código máquina directamente?", True),
        ("¿La recursión es una técnica donde una función se llama a sí misma?", True),
        ("¿Los arrays son estructuras de datos dinámicas en la mayoría de los lenguajes?", False),
        ("¿Una variable global solo es accesible dentro de la función en la que se declara?", False),
        ("¿El principio DRY significa 'Don't Repeat Yourself'?", True),
        ("¿Un bucle 'for' siempre necesita una condición de terminación explícita?", False),
        ("¿El testing unitario verifica componentes individuales del software?", True),
        ("¿La optimización prematura es generalmente considerada una mala práctica en programación?", True),
        ("¿La memoria dinámica es gestionada manualmente en todos los lenguajes de programación?", False),
        ("¿Un 'stack overflow' ocurre cuando se excede la capacidad del stack?", True),
        ("¿La programación concurrente permite la ejecución simultánea de múltiples tareas?", True),
        ("¿El polimorfismo permite tratar objetos de diferentes tipos de forma uniforme?", True),
        ("¿La encapsulación es el concepto de esconder la implementación interna de un objeto?", True),
        ("¿Un sistema de tipos estático permite detectar errores de tipo en tiempo de ejecución?", False),
        ("¿El 'big-O' notation se utiliza para describir la eficiencia de un algoritmo?", True),
        ("¿Un 'deadlock' ocurre cuando dos o más procesos se bloquean mutuamente esperando recursos?", True),
        ("¿La memoria caché es más lenta que la memoria principal (RAM)?", False),
        ("¿Los patrones de diseño (design patterns) son soluciones reutilizables a problemas comunes en el desarrollo de software?", True),
        ("¿En programación orientada a objetos, 'herencia' permite crear nuevas clases basadas en clases existentes?", True),
        ("¿La modularidad ayuda a dividir un programa en partes manejables y reutilizables?", True),
        ("¿La complejidad espacial mide el tiempo que tarda un algoritmo en ejecutarse?", False),
        ("¿Una interfaz en programación es una colección de métodos que una clase puede implementar?", True),
        ("¿La programación declarativa se enfoca en describir 'cómo' lograr una tarea?", False),
        ("¿Un hilo (thread) es una unidad de ejecución dentro de un proceso?", True),
        ("¿Los árboles binarios son una estructura de datos jerárquica donde cada nodo tiene como máximo dos hijos?", True),
        ("¿Un algoritmo de búsqueda binaria funciona eficientemente en listas desordenadas?", False),
        ("¿El concepto de 'backtracking' se utiliza para resolver problemas de manera tentativa y retrocediendo cuando es necesario?", True),
        ("¿La notación 'LIFO' se refiere a 'Last In, First Out'?", True),
        ("¿El patrón de diseño 'singleton' asegura que una clase solo tenga una instancia?", True),
        ("¿La sobrecarga de métodos permite tener varias funciones con el mismo nombre pero diferentes parámetros?", True),
        ("¿La programación asíncrona permite realizar múltiples tareas de manera secuencial?", False),
        ("¿La coherencia de caché es un problema que surge en sistemas de multiprocesamiento?", True),
        ("¿Una cola (queue) sigue el principio FIFO, 'First In, First Out'?", True),
        ("¿El principio SOLID incluye cinco principios fundamentales para la programación orientada a objetos?", True),
        ("¿La programación imperativa se basa en comandos que cambian el estado del programa?", True),
        ("¿El análisis estático de código implica la ejecución del programa para detectar errores?", False),
        ("¿Un sistema distribuido consiste en múltiples nodos que trabajan juntos para resolver una tarea?", True),
        ("¿La persistencia de datos asegura que los datos no se pierdan cuando se apaga el sistema?", True),
        ("¿La técnica de 'divide y vencerás' implica dividir un problema grande en subproblemas más pequeños?", True),
        ("¿Una función 'pura' en programación funcional no tiene efectos secundarios?", True),
        ("¿El patrón de diseño 'factory' delega la creación de objetos a una clase o método separado?", True),
        ("¿El garbage collection gestiona automáticamente la liberación de memoria en algunos lenguajes?", True),
        ("¿El concepto de 'acoplamiento' se refiere a qué tan dependientes son entre sí los módulos de un sistema?", True),
        ("¿Un compilador traduce el código fuente línea por línea en tiempo de ejecución?", False),
        ("¿El principio KISS ('Keep It Simple, Stupid') sugiere mantener el diseño de software lo más simple posible?", True)
    ]

    HURLINGHAM = [
    ("¿Hurlingham es una ciudad ubicada en la provincia de Buenos Aires?", True),
    ("¿El partido de Hurlingham se creó en 1994?", True),
    ("¿Hurlingham limita con la Ciudad Autónoma de Buenos Aires?", False),
    ("¿El nombre 'Hurlingham' proviene de una ciudad inglesa?", True),
    ("¿El Hurlingham Club fue fundado en 1888?", True),
    ("¿El Hurlingham Club es conocido por ser un club de polo?", True),
    ("¿El partido de Hurlingham tiene acceso a la línea de tren San Martín?", True),
    ("¿Hurlingham es parte del Gran Buenos Aires?", True),
    ("¿El primer intendente de Hurlingham fue Juan José Álvarez?", True),
    ("¿El área total del partido de Hurlingham es menor a 50 km²?", True),
    ("¿El arroyo Morón atraviesa Hurlingham?", True),
    ("¿La Universidad Nacional de Hurlingham fue fundada en 2014?", True),
    ("¿La localidad de Villa Tesei es parte del partido de Hurlingham?", True),
    ("¿Hurlingham tiene más de 200,000 habitantes?", True),
    ("¿El Centro Cultural Leopoldo Marechal está ubicado en Hurlingham?", True),
    ("¿El poeta Leopoldo Marechal tiene una calle con su nombre en Hurlingham?", True),
    ("¿Hurlingham celebra anualmente una fiesta del Día del Niño en sus parques?", True),
    ("¿El Polideportivo Municipal de Hurlingham se utiliza para eventos deportivos y culturales?", True),
    ("¿La Fiesta de la Virgen de la Guardia se celebra en Hurlingham?", True),
    ("¿El Hospital San Bernardino es uno de los principales hospitales de Hurlingham?", True),
    ("¿El Estadio Municipal de Hurlingham es sede de competencias de atletismo?", True),
    ("¿La ciudad de Hurlingham tiene una estación de tren llamada 'Hurlingham'?", True),
    ("¿El transporte público en Hurlingham incluye colectivos y trenes?", True),
    ("¿El club de rugby Curupaytí tiene sede en Hurlingham?", True),
    ("¿El Hurlingham Club fue originalmente un club social exclusivo para británicos?", True),
    ("¿En Hurlingham se pueden encontrar muchas áreas verdes y parques?", True),
    ("¿Hurlingham tiene su propia catedral?", False),
    ("¿Hurlingham es conocida por su gran cantidad de clubes deportivos?", True),
    ("¿La Avenida Vergara es una de las principales arterias de Hurlingham?", True),
    ("¿El fútbol es el deporte más practicado en Hurlingham?", False, "El polo y rugby también tienen gran relevancia"),
    ("¿El Club Atlético y Social Hurlingham fue fundado en 1941?", True),
    ("¿El municipio de Hurlingham tiene más de tres localidades?", False, "Hurlingham tiene tres localidades: Hurlingham, Villa Tesei, y William Morris"),
    ("¿William Morris es una localidad que pertenece al partido de Hurlingham?", True),
    ("¿El tren San Martín pasa por Hurlingham?", True),
    ("¿La Feria del Libro de Hurlingham se celebra todos los años?", True),
    ("¿El río Reconquista pasa por Hurlingham?", True),
    ("¿El Escudo de Hurlingham tiene elementos que representan su historia inglesa?", True),
    ("¿La ciudad de Hurlingham tiene un jardín botánico?", False),
    ("¿El Colegio Ward, ubicado en Villa Sarmiento, se encuentra en Hurlingham?", False),
    ("¿El Hospital Posadas está ubicado en Hurlingham?", False, "El Hospital Posadas está en El Palomar, cercano a Hurlingham"),
    ("¿El Hurlingham Polo Club es uno de los más antiguos de Argentina?", True),
    ("¿Hurlingham es conocida por ser una ciudad predominantemente industrial?", False),
    ("¿La ciudad de Hurlingham tiene un acceso directo a la Autopista del Oeste?", True),
    ("¿El tren Sarmiento tiene una estación en Hurlingham?", False, "El tren San Martín es el que pasa por Hurlingham"),
    ("¿Hurlingham es famosa por su tradición agrícola?", False, "Es una ciudad mayormente residencial con áreas verdes y clubes sociales"),
    ("¿Existen festivales culturales y gastronómicos en Hurlingham?", True),
    ("¿La Parroquia San Pablo es un punto de referencia en Hurlingham?", True),
    ("¿La estación de tren William Morris se encuentra en Hurlingham?", True),
    ("¿Hurlingham limita al este con el partido de Morón?", True),
    ("¿La ciudad de Hurlingham tiene una universidad pública?", True)
    ]

    SOFTWARE_LIBRE = [
    ("¿El software libre es aquel que garantiza la libertad de uso, estudio, modificación y distribución?", True),
    ("¿El proyecto GNU fue uno de los primeros en promover el software libre?", True),
    ("¿Richard Stallman es el fundador del movimiento del software libre?", True),
    ("¿El software libre tiene que ser siempre gratuito?", False),
    ("¿La licencia GPL es una de las más comunes en software libre?", True),
    ("¿El código fuente del software libre está disponible para cualquier persona?", True),
    ("¿La Free Software Foundation fue creada en 1985?", True),
    ("¿La licencia MIT es una licencia de software libre?", True),
    ("¿El software de código abierto y el software libre son lo mismo?", False),
    ("¿Linux es un ejemplo de software libre?", True),
    ("¿La libertad de redistribuir copias del software es una de las cuatro libertades del software libre?", True),
    ("¿El movimiento del software libre fue iniciado en la década de 1990?", False, "Fue iniciado en la década de 1980"),
    ("¿El software libre permite a los usuarios modificar el código fuente y redistribuir sus versiones modificadas?", True),
    ("¿Un software con licencia privativa es considerado software libre?", False),
    ("¿La Open Source Initiative (OSI) promueve el software libre?", False, "Promueve el software de código abierto"),
    ("¿Ubuntu es una distribución de Linux que se considera software libre?", True),
    ("¿El software bajo licencia Apache es considerado software libre?", True),
    ("¿El software libre fomenta el monopolio de grandes empresas tecnológicas?", False),
    ("¿La FSF (Free Software Foundation) es responsable de la creación de la licencia GPL?", True),
    ("¿Firefox es un navegador de software libre?", True),
    ("¿El kernel de Linux fue creado por Linus Torvalds?", True),
    ("¿Se puede vender software libre?", True),
    ("¿La libertad de ejecutar el software para cualquier propósito es una de las libertades del software libre?", True),
    ("¿El software libre no puede ser utilizado para fines comerciales?", False),
    ("¿La licencia BSD es compatible con el software libre?", True),
    ("¿La diferencia principal entre software libre y software privativo es el acceso al código fuente?", True),
    ("¿GNU es un sistema operativo completamente libre?", True),
    ("¿El software libre excluye la posibilidad de usarlo para investigaciones militares?", False),
    ("¿Git es un sistema de control de versiones distribuido que se considera software libre?", True),
    ("¿MySQL es un software libre bajo licencia GPL?", True),
    ("¿El software libre promueve el control de los usuarios sobre el software que utilizan?", True),
    ("¿Freeware y software libre son términos equivalentes?", False),
    ("¿El software libre fomenta la colaboración entre desarrolladores?", True),
    ("¿GPL es una licencia de software libre copyleft?", True),
    ("¿El software libre puede estar disponible en binario, sin acceso al código fuente?", False),
    ("¿El término 'copyleft' implica que los derechos del software libre son siempre cedidos al dominio público?", False),
    ("¿Blender, el software de modelado 3D, es software libre?", True),
    ("¿El software libre permite su redistribución bajo licencias privativas?", False),
    ("¿El sistema operativo Debian es un proyecto de software libre?", True),
    ("¿El software libre siempre garantiza la seguridad del usuario?", False, "La seguridad depende de la calidad del código y su mantenimiento"),
    ("¿El software bajo licencia AGPL debe compartir el código incluso si es ejecutado como un servicio en la web?", True),
    ("¿OpenOffice es un ejemplo de software libre?", True),
    ("¿La libertad de estudiar el funcionamiento del software es una característica esencial del software libre?", True),
    ("¿El concepto de 'licencia copyleft' asegura que las versiones derivadas de software libre también sean libres?", True),
    ("¿Es obligatorio que todas las modificaciones hechas a un software libre se publiquen?", False),
    ("¿El software libre es exclusivo para usuarios avanzados y programadores?", False),
    ("¿El sistema operativo Android se basa en software libre?", True),
    ("¿El proyecto Mozilla promueve el software libre?", True),
    ("¿Se puede usar software libre en la educación y la investigación científica?", True),
    ("¿El movimiento de software libre busca eliminar todas las patentes de software?", True)
    ]

    TECNOLOGIA = [
    ("¿HTML es un lenguaje de programación?", False),
    ("¿Un terabyte es mayor que un gigabyte?", True),
    ("¿El protocolo HTTPS es más seguro que HTTP?", True),
    ("¿JavaScript y Java son el mismo lenguaje de programación?", False),
    ("¿Almacenar en la nube se refiere a guardar datos en servidores accesibles por Internet?", True),
    ("¿La inteligencia artificial y el aprendizaje automático son lo mismo?", False),
    ("¿El navegador web Google Chrome fue lanzado antes que Mozilla Firefox?", False),
    ("¿El cifrado de datos se usa para proteger la información de accesos no autorizados?", True),
    ("¿La tecnología blockchain se utiliza principalmente en las criptomonedas?", True),
    ("¿Un disco SSD es más rápido que un disco HDD tradicional?", True),
    ("¿Un smartwatch es un tipo de wearable?", True),
    ("¿La realidad aumentada y la realidad virtual son lo mismo?", False),
    ("¿El lenguaje SQL se utiliza para gestionar bases de datos?", True),
    ("¿El formato de imagen JPEG es un formato sin pérdida de calidad?", False),
    ("¿Python es un lenguaje utilizado para desarrollo web y análisis de datos?", True),
    ("¿5G es la cuarta generación de tecnología móvil?", False, "Es la quinta generación"),
    ("¿El término 'Internet de las cosas' se refiere a la interconexión de dispositivos a través de Internet?", True),
    ("¿Apple lanzó su primer iPhone en 2007?", True),
    ("¿El código QR es una tecnología utilizada principalmente para realizar pagos?", False, "Su uso principal es el almacenamiento de información legible por dispositivos"),
    ("¿Los discos Blu-ray tienen más capacidad que los DVD?", True),
    ("¿Un CPU es considerado el cerebro de una computadora?", True),
    ("¿JavaScript es un lenguaje interpretado?", True),
    ("¿El sistema operativo Android fue desarrollado inicialmente por Google?", False, "Fue desarrollado por Android Inc., que luego fue adquirida por Google"),
    ("¿Un píxel es la unidad básica de una imagen digital?", True),
    ("¿Linux es un sistema operativo de código abierto?", True),
    ("¿Las impresoras 3D solo pueden imprimir en plástico?", False, "Pueden imprimir en diversos materiales como metal, resina y hasta comida"),
    ("¿El algoritmo es un conjunto de instrucciones o reglas para resolver un problema?", True),
    ("¿Los smartphones modernos suelen tener más de una cámara trasera?", True),
    ("¿El lenguaje C fue desarrollado después de Python?", False),
    ("¿El sistema operativo Windows fue lanzado antes que macOS?", False, "macOS (anteriormente Mac OS) fue lanzado antes que Windows"),
    ("¿El protocolo TCP/IP es el principal protocolo de comunicación en Internet?", True),
    ("¿El almacenamiento flash se usa comúnmente en unidades USB?", True),
    ("¿Las redes Wi-Fi utilizan ondas de radio para transmitir datos?", True),
    ("¿La nube híbrida combina servicios de nube privada y pública?", True),
    ("¿Los dispositivos IoT siempre necesitan una conexión a Internet para funcionar?", False, "Algunos dispositivos IoT pueden funcionar localmente sin Internet"),
    ("¿El navegador web Netscape fue uno de los primeros navegadores populares?", True),
    ("¿El lenguaje Swift fue creado por Apple?", True),
    ("¿Un firewall protege las redes de accesos no autorizados?", True),
    ("¿El formato de archivo PNG permite transparencia?", True),
    ("¿La energía renovable es una tecnología utilizada para generar electricidad de fuentes naturales como el sol y el viento?", True),
    ("¿El término 'big data' se refiere al manejo de grandes cantidades de información?", True),
    ("¿El asistente de voz Alexa fue desarrollado por Google?", False, "Fue desarrollado por Amazon"),
    ("¿Los discos duros de estado sólido (SSD) tienen partes móviles?", False),
    ("¿Una dirección IP es un identificador único para un dispositivo en una red?", True),
    ("¿El estándar USB 3.0 es más rápido que USB 2.0?", True),
    ("¿Un código de barras es un ejemplo de una tecnología de identificación automática?", True),
    ("¿El lenguaje de programación COBOL es ampliamente utilizado en el desarrollo de videojuegos modernos?", False),
    ("¿El reconocimiento facial es una tecnología basada en inteligencia artificial?", True),
    ("¿Un dominio web es una dirección única que identifica a un sitio web?", True)
]
